version: '3.4'

services:

  catalog.api:
    container_name: "catalog.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog.db:27017"
    ports:
      - "9000:80"
    depends_on:
      - catalog.db

  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 