version: '3.4'

services:

  catalog.api:
    container_name: "catalog.api"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=mongodb://catalog.db:27017"
    ports:
      - "8000:80"
    depends_on:
      - catalog.db

  catalog.db:
    container_name: catalog.db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db 
  
  discount.db:
    container_name: discount.db
    environment: 
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_DB=discount_db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@aspnetrun.com
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin

  basket.db:
    container_name: basket.db
    restart: always
    ports:
      - "6379:6397"

  basket.api:
    container_name: baset.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "CacheSettings:ConnectionString=basket.db:6379"
    depends_on:
      - basket.db
    ports:
      - "8001:80"

  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - portainer_data:/data portainer/portainer-ce
      - /var/run/docker.sock:/var/run/docker.sock 

  discount.api:
    container_name: discount.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings:ConnectionString=Server=discount.db;Port=5432;Database=discount_db;User Id=admin;Password=admin1234;"
    ports:
      - "8002:80"
    depends_on:
      - discount.db
