version: '3.4'

services:

  catalog.db:
    image: mongo

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalog.api
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.Api/Dockerfile

volumes:
  mongo_data: